### ISSUE TITLE
Requirement resolves to wrong version

### ISSUE THREAD

**Issue by ameenross** [bldr-io/bldr#138]
I have the following `bldr.json`

```json
{
    "require": {
        "squizlabs/php_codesniffer": "~2.1.0"
    }
}
```

Upon running `bldr install`, I'm getting the following error:
> Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - The requested package squizlabs/php_codesniffer 1.5.6 could not be found.

This is strange for 2 reasons:

1. The version it wants to install is lower than my requirement
2. Version 1.5.6 is an existing release, but it fails to install

**Comment by aequasi** [comment]
Are you using the phar, or are you including bldr?

**Comment by aequasi** [comment]
fixed in 7.3.0

**Comment by ameenross** [comment]
I'm using the phar, which I built from master. I just rebuilt the phar and tried again, but it still gives me this error.

**Comment by ameenross** [comment]
Is it possible to reference the version of `phpcs` that is included in the phar?

**Comment by aequasi** [comment]
~2.0 should match your ~2.1.0 just fine.... Little confused as to why you are getting an error on that.

**Comment by ameenross** [comment]
Hmm, I must have made a mistake building. It doesn't give me that error anymore, but it still does not install the dependency. I guess it doesn't since the phar already satisfies that dependency. Other packages install fine.

I guess that leaves 2 separate problems:

1. If my project requires a newer version of a package that is already embedded in the phar, that will be problematic, and perhaps only possible with a fork of the package.
2. Since `phpcs` is embedded in the phar, it would make sense to be able to use it in your `.bldr.yml`. I have been unable to do so thus far. Perhaps a bldr-codesniffer block needs to be created just for this purpose?

**Comment by aequasi** [comment]
I think i'm just going to change the way the phar is built, so it doesn't build the phar with require-dev dependencies... Should help. Doing 2 would be nice, but im not sure thats possible without doing an external block. Which would require doing a `bldr install` any time you want to use it.

**Comment by ameenross** [comment]
Right. I'd like to create that block

**Comment by aequasi** [comment]
Heh, I was actually thinking about a php helper block: #8 but i closed it, wasnt sure people would use it. If you'd like, I could create the block for you

**Comment by ameenross** [comment]
That would be a very useful tool for people like me who strictly enforce coding standards, especially when reviewing other people's code. It's the primary reason I'm using task runners.

If you could create it that would be great. I think it would be Nice if the autocorrect feature can also be used.

**Comment by aequasi** [comment]
What should we name it?

**Comment by ameenross** [comment]
Bldr-phpcs?

**Comment by aequasi** [comment]
i was thinking one for all of the tasks in #8, does php-tasks-block work?

**Comment by ameenross** [comment]
Hmm, you could, but do you think it is a good idea? I'm not sure about tasks in the name, doesn't a block imply tasks? Or are there other block types possible? If so, then perhaps php-tasks is sufficient.

**Comment by aequasi** [comment]
Hmm... Let me think about it some more.

**Comment by ameenross** [comment]
Let's continue discussion of the package in the other issue.

**Comment by aequasi** [comment]
Alrighty, sorry, i was away from my computer all weekend
